[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "preserve"